debug: false
# Springframework設定
spring: 
  application.name: container-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  profiles:
    default: jpa

# actuator設定
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: "http://localhost:4317"
            
# ログ設定
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [traceId=%X{traceId}, spanId=%X{spanId}] %msg%n"

