debug: false
# Springframework設定
spring: 
  application.name: container-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  profiles:
    default: jpa

# actuator設定
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  metrics:
    tags:
      application: server_app
      instance: "host.docker.internal:8080"
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        # "/v1/metrics"はcollectorのexporterが付加するが直接接続の場合は必要
        url: "http://tsukumo:9090/api/v1/otlp/v1/metrics"
        step: 2s
    logging:
      endpoint: "http://tsukumo:3100/otlp/v1/logs"

tracing:
  url: "http://localhost:4317"
            
# ログ設定
logging:
  level:
    org.springframework.boot.logging: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [traceId=%X{traceId}, spanId=%X{spanId}] %msg%n"
